# Generated by Django 4.1.2 on 2022-11-03 07:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_topic_post_author_message_post_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
