# Generated by Django 3.2.7 on 2022-11-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_note_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date']},
        ),
    ]
