# Generated by Django 3.2.7 on 2022-11-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='f',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
