# Generated by Django 4.1.2 on 2022-11-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
