# Generated by Django 3.2.7 on 2022-11-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
