# Generated by Django 3.2.7 on 2022-12-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_challenge_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='day_created',
            new_name='date_created',
        ),
    ]
