# Generated by Django 3.2.7 on 2022-12-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_alter_hint_quizz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
