# Generated by Django 3.2.7 on 2022-12-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_quizz_file_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
