# Generated by Django 3.2.7 on 2022-12-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
